import { inter } from '@/app/ui/fonts';
import '@/app/ui/global.css'

export const metadata = {
  title: "Book Diary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-[20px] box-content`}>{children}</body>
    </html>
  );
}
